Repository GDSC-SWU/2023-Medisight-SolutionChallenge, pull requests merged in 2023-03, with the labels that each got.

#19 MDS-74 feat: QR scanner 기능 구현
  main.spec
  medisight/lib/page/search_result.dart
  medisight/lib/screen/camera_screen.dart
  medisight/lib/screen/shoot_qr.dart
  medisight/pubspec.lock
  medisight/pubspec.yaml
Labels: feature

#20 MDS-67 튜토리얼 페이지 제작
  medisight/lib/screen/intro_page_1.dart
  medisight/lib/screen/intro_page_2.dart
  medisight/lib/screen/intro_page_3.dart
  medisight/lib/screen/intro_page_4.dart
  medisight/lib/screen/tuto_screen.dart
  medisight/pubspec.yaml
Labels: feature

#22 MDS-76 테마 설정 페이지
  medisight/lib/screen/theme_screen.dart
  medisight/lib/theme/animated_toggle_button.dart
  medisight/lib/theme/theme.dart
  medisight/lib/theme/theme_provider.dart
Labels: feature

#23 MDS-79 상식 내용 삽입
  medisight/lib/page/tip_content.dart
  medisight/lib/page/tip_sub_1.dart
  medisight/lib/page/tip_sub_2.dart
  medisight/lib/page/tip_sub_3.dart
  medisight/lib/page/tip_sub_4.dart
  medisight/lib/screen/info_screen.dart
  medisight/lib/widget/grid_button.dart
  medisight/lib/widget/grid_button_1.dart
  medisight/lib/widget/grid_button_2.dart
  medisight/lib/widget/grid_button_3.dart
  medisight/lib/widget/grid_button_4.dart
Labels: feature

#25 MDS-81 UI 변경
  medisight/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  medisight/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  medisight/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  medisight/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  medisight/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  medisight/assets/images/img_alarm.png
  medisight/assets/images/img_camera.png
  medisight/assets/images/img_info.png
  medisight/assets/images/img_map.png
  medisight/assets/images/img_search.png
  medisight/assets/images/medisight_logo.png
  medisight/lib/main.dart
  medisight/lib/page/home.dart
  medisight/lib/provider/CustomCheckBoxGroup.dart
  medisight/lib/screen/camera_screen.dart
  medisight/lib/screen/disease_select.dart
  medisight/lib/screen/map_screen.dart
  medisight/lib/screen/medi_screen.dart
  medisight/lib/screen/mypage_screen.dart
  medisight/lib/screen/permission_request_screen.dart
  medisight/lib/screen/search_screen.dart
  medisight/lib/screen/shoot_medi.dart
  medisight/lib/screen/update_alarm.dart
  medisight/lib/widget/login_widget.dart
  medisight/test/widget_test.dart
Labels: feature

#26 MDS-70 직접 검색 API 구현
  backend/routes/Search.js
Labels: backend, feature

#27 MDS-84 지도 API 구현
  backend/app.js
  backend/routes/Map.js
Labels: backend, feature

#29 MDS-83 지도 페이지 구현
  medisight/android/app/src/main/AndroidManifest.xml
  medisight/assets/audios/route_changed.mp3
  medisight/lib/podo/route_info.dart
  medisight/lib/podo/route_map_info.dart
  medisight/lib/screen/home_screen.dart
  medisight/lib/screen/map_route_screen.dart
  medisight/lib/screen/map_screen.dart
  medisight/lib/widget/route_instruction_widget.dart
  medisight/lib/widget/route_map_widget.dart
  medisight/pubspec.lock
  medisight/pubspec.yaml
Labels: feature

#31 MDS-77 기저질환 알림 다이얼로그 구현
  medisight/lib/page/search_result.dart
Labels: feature

#30 MDS-78 직접 검색 키워드 삭제 시의 동작 수정 및 페이지 연결
  medisight/lib/page/search_list.dart
  medisight/lib/screen/home_screen.dart
Labels: feature

#32 MDS-87 유효기간/원료성분 response 구조 수정
  backend/routes/Search.js
Labels: bug, backend

#33 MDS-45 검색 결과 상세 페이지 구현
  medisight/lib/page/search_result_content.dart
  medisight/lib/podo/search_result_category.dart
  medisight/lib/screen/shoot_qr.dart
Labels: feature

#35 MDS-89 어시스턴트 연결
  medisight/android/app/src/main/AndroidManifest.xml
  medisight/lib/screen/bottom_navi.dart
Labels: feature

#34 MDS-88 homeScreen ui 수정
  medisight/lib/screen/home_screen.dart
Labels: feature

#36 MDS-90 어시스턴트 런타임 에러 해결
  medisight/lib/screen/bottom_navi.dart
Labels: bug

#38 MDS-92 feat: 카메라 tts 연결
  medisight/lib/screen/create_alarm.dart
  medisight/lib/screen/shoot_medi.dart
  medisight/lib/screen/shoot_period.dart
  medisight/lib/screen/shoot_qr.dart
Labels: enhancement, feature

#40 MDS-94 튜토리얼 텍스트 입력
  medisight/lib/screen/intro_page_1.dart
  medisight/lib/screen/intro_page_2.dart
  medisight/lib/screen/intro_page_3.dart
  medisight/lib/screen/intro_page_4.dart
Labels: feature

#39 MDS-93 알람 유효기간 촬영 연결
  medisight/lib/screen/camera_screen.dart
  medisight/lib/screen/create_alarm.dart
  medisight/lib/screen/medi_screen.dart
  medisight/lib/screen/shoot_period.dart
  medisight/lib/screen/update_alarm.dart
Labels: feature

#43 MDS-95 지도 페이지 성능 개선
  medisight/lib/screen/map_route_screen.dart
  medisight/lib/widget/route_instruction_widget.dart
  medisight/lib/widget/route_map_widget.dart
Labels: feature

#44 MDS-98 알람 피드백 반영
  medisight/assets/audios/ringtone.mp3
  medisight/lib/provider/CustomCheckBoxGroup.dart
  medisight/lib/screen/alarm_screen.dart
  medisight/lib/screen/create_alarm.dart
  medisight/lib/screen/update_alarm.dart
  medisight/lib/service/alarm_scheduler.dart
  medisight/lib/theme/theme.dart
Labels: bug, feature

#47 MDS-100 feat: Add tts and Connect camera on navi
  medisight/lib/page/home.dart
  medisight/lib/screen/bottom_navi.dart
  medisight/lib/screen/disease_select.dart
  medisight/lib/screen/mypage_screen.dart
Labels: feature

#50 MDS-103 Fix: 내비게이션 버그 수정 및 커스텀
  medisight/lib/page/home.dart
  medisight/lib/screen/bottom_navi.dart
  medisight/lib/screen/disease_select.dart
  medisight/pubspec.lock
  medisight/pubspec.yaml
Labels: bug, feature

#51 MDS-111 UI overflow 버그 픽스
  medisight/assets/images/2.0x/img_pharmacy.png
  medisight/assets/images/2.0x/img_question.png
  medisight/assets/images/2.0x/img_store.png
  medisight/assets/images/3.0x/img_pharmacy.png
  medisight/assets/images/3.0x/img_question.png
  medisight/assets/images/3.0x/img_store.png
  medisight/lib/screen/camera_screen.dart
  medisight/lib/screen/info_screen.dart
  medisight/lib/screen/intro_page_1.dart
  medisight/lib/screen/intro_page_4.dart
  medisight/lib/screen/map_screen.dart
  medisight/lib/screen/tuto_screen.dart
  medisight/lib/widget/route_instruction_widget.dart
  medisight/pubspec.yaml
Labels: bug

#52 MDS-112 bottom navi 수정
  medisight/lib/screen/bottom_navi.dart
Labels: feature

#53 MDS-106 지도 페이지 라우팅 버그 패치
  medisight/lib/screen/map_route_screen.dart
  medisight/lib/widget/route_instruction_widget.dart
  medisight/lib/widget/route_map_widget.dart
Labels: bug
