Repository GDSC-SWU/2023-Medisight-SolutionChallenge, pull requests merged in 2023-04, with the labels that each got.

#55 MDS-114 내비게이션 플로팅 버튼 오류 해결
  medisight/lib/screen/bottom_navi.dart
Labels: bug

#56 MDS-115 알람 수정 페이지 오류 수정
  medisight/lib/screen/bottom_navi.dart
  medisight/lib/screen/update_alarm.dart
Labels: bug

#57 MDS-116 내비게이션바 에러 해결
  medisight/lib/screen/bottom_navi.dart
Labels: bug

#58 MDS-119 최종 UI 수정 및 버그 해결
  medisight/fonts/Noto_Sans_KR/OFL.txt
  medisight/lib/screen/mypage_screen.dart
  medisight/lib/screen/permission_request_screen.dart
  medisight/lib/screen/shoot_medi.dart
  medisight/lib/screen/update_alarm.dart
Labels: bug, feature

#59 MDS-120 촬영 시간 수정
  medisight/lib/screen/shoot_qr.dart
Labels: feature

#61 MDS-122 [!HOTFIX] 백엔드 에러 핸들링 및 버그 패치
  backend/package-lock.json
  backend/package.json
  backend/prisma/migrations/20230406023120_init/migration.sql
  backend/prisma/schema.prisma
  backend/routes/Map.js
  backend/util/Database.js
Labels: bug, backend

#62 MDS-122 [!HOTFIX] 백엔드 API end point 수정 및 쿼리 변경
  backend/package-lock.json
  backend/package.json
  backend/util/Database.js
  backend/util/OpenAPI.js
Labels: bug, backend

#63 MDS-122 [!HOTFIX] 공공데이터 에러 핸들링 및 비동기 패치
  backend/package-lock.json
  backend/package.json
  backend/util/Database.js
  backend/util/OpenAPI.js
Labels: bug, backend
